import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const fixture={base:process.env.MTANALOG_BROWSER_URL||'http://127.0.0.1:8790'};
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']});
if(process.env.MTANALOG_BROWSER_LINK_FILE){
  const link=new URL(readFileSync(process.env.MTANALOG_BROWSER_LINK_FILE,'utf8').trim());
  const token=new URLSearchParams(link.hash.slice(1)).get('access');
  const create=browser.newContext.bind(browser);
  browser.newContext=async options=>{
    const context=await create(options);
    await context.addCookies([{name:'__Host-mianalog-access',value:token,url:fixture.base,secure:true,httpOnly:true,sameSite:'Lax'}]);
    return context;
  };
}
const errors=[];
try{
  const context=await browser.newContext({viewport:{width:1440,height:1150},deviceScaleFactor:1});
  const page=await context.newPage();
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(fixture.base);
  assert.equal(await page.locator('#login, #logout').count(),0);
  await page.locator('#dashboard').waitFor({state:'visible'});
  await page.locator('#loading').waitFor({state:'hidden'});
  assert.equal((await page.request.get(fixture.base+'/api/chart')).status(),200);

  assert.equal(new URL(page.url()).hash,'');
  assert.notEqual(await page.locator('#last-price').innerText(),'—');
  await page.evaluate(async()=>{await document.fonts.ready;for(let i=0;i<4;i++)await new Promise(requestAnimationFrame);});
  // A moving crosshair must reuse the rendered candle image.
  const hoverWork=await page.evaluate(async()=>{
    const {Charts}=await import('/chart.js'),original=Charts.prototype.drawCandles;let rebuilds=0;
    Charts.prototype.drawCandles=function(...args){rebuilds++;return original.apply(this,args);};
    const canvas=document.querySelector('#heatmap'),r=canvas.getBoundingClientRect();
    for(let i=0;i<8;i++){canvas.dispatchEvent(new PointerEvent('pointermove',{clientX:r.left+80+i*12,clientY:r.top+100,pointerType:'mouse'}));await new Promise(requestAnimationFrame);}
    Charts.prototype.drawCandles=original;return rebuilds;
  });
  assert.equal(hoverWork,0,'Pointer movement should reuse the candle layer');
  await page.evaluate(()=>document.fonts.ready);
  assert.ok(await page.evaluate(()=>document.fonts.check('14px Montserrat')),'Local Montserrat font must load');
  assert.equal(await page.locator('#connection').evaluate(el=>el.closest('.panel-heading').querySelector('#heatmap-title')!==null),true,'Collector status belongs in liquidity heading');
  const clockCheck=await page.evaluate(async()=>{
    const original=Date.now,wasLive=document.querySelector('#connection').textContent.includes('Live');
    Date.now=()=>original()+300000;
    try{await new Promise(resolve=>setTimeout(resolve,5500));return !wasLive||!document.querySelector('#connection').textContent.includes('неактивен');}
    finally{Date.now=original;}
  });
  assert.equal(clockCheck,true,'Phone wall-clock skew must not mark a live collector inactive');
  assert.match(await page.locator('#utc-clock').innerText(),/^\d{2}:\d{2}:\d{2} UTC$/);
  assert.equal(await page.locator('.flow-card .panel-icon').count(),1);
  assert.match(await page.title(),/^FireCharts/);
  assert.match(await page.locator('.brand').innerText(),/FireCharts/);
  const changeColors=await page.locator('#price-change').evaluate(el=>{
    const negative=el.classList.contains('negative');el.classList.remove('negative');
    const positive=getComputedStyle(el).color;el.classList.add('negative');const minus=getComputedStyle(el).color;
    el.classList.toggle('negative',negative);return {positive,minus};
  });
  assert.deepEqual(changeColors,{positive:'rgb(187, 239, 31)',minus:'rgb(255, 0, 85)'});
  assert.equal(await page.locator('html').getAttribute('data-client'),'desktop');
  assert.match(await page.locator('.chart-hint').innerText(),/Колесо/);
  for(const [width,height] of [[1366,768],[1920,1080],[2560,1440],[900,800]]){
    await page.setViewportSize({width,height});
    await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Desktop horizontal overflow');
    const main=await page.locator('.main-column').boundingBox(),side=await page.locator('.sidebar').boundingBox();
    if(width>=1024)assert.ok(side.x>=main.x+main.width,'Desktop settings must sit beside charts');
    else assert.ok(side.y>main.y,'Narrow desktop must stack without becoming a phone');
    const history=await page.locator('.sidebar-secondary .info-card').first().boundingBox(),help=await page.locator('#controls-help').boundingBox();
    assert.ok(help.y>=history.y+history.height&&help.y-history.y-history.height<24,'Help must follow history without a stretched gap');
    assert.equal(await page.locator('html').getAttribute('data-client'),'desktop');
  }
  await page.setViewportSize({width:1440,height:1150});
  await page.locator('#heatmap').focus();
  const keyboardBefore=await page.locator('#heatmap').screenshot();
  await page.keyboard.press('+');
  const keyboardAfter=await page.locator('#heatmap').screenshot();assert.ok(!keyboardBefore.equals(keyboardAfter),'Keyboard zoom must work');
  await page.keyboard.press('ArrowLeft');await page.keyboard.press('0');
  await page.locator('#heatmap').hover();assert.equal(await page.locator('.chart-loupe:visible').count(),0);
  await page.screenshot({path:'output/web_desktop.png',fullPage:true});
  await page.locator('[data-period="1w"]').click();
  await page.waitForFunction(()=>document.querySelector('#price-range').textContent==='±10%');
  assert.equal(await page.locator('[data-period="1w"]').getAttribute('aria-pressed'),'true');
  await page.locator('[data-filter="percentile"]').click();
  await page.locator('#percentile-controls').waitFor({state:'visible'});
  await page.locator('#percentile-low').fill('85');
  await page.locator('#percentile-low').dispatchEvent('input');
  assert.equal(await page.locator('#percentile-low-value').innerText(),'85%');
  await page.locator('[data-cvd="normalized"]').click();
  assert.equal(await page.locator('#cvd-legend button').count(),6);
  assert.doesNotMatch(await page.locator('#cvd-legend').innerText(),/< \$100|≥ \$10M/);
  assert.equal(await page.locator('#cvd-legend .series-total').count(),1);
  const legend=page.locator('#cvd-legend button').first();
  await legend.click();assert.equal(await legend.getAttribute('aria-pressed'),'false');
  await legend.click();
  await page.locator('#heatmap').scrollIntoViewIfNeeded();
  const heat=await page.locator('#heatmap').boundingBox();
  await page.mouse.move(heat.x+heat.width*.5,heat.y+heat.height*.4);
  await page.locator('#heatmap-tooltip').waitFor({state:'visible'});
  assert.match(await page.locator('#heatmap-tooltip').innerText(),/UTC/);
  await page.mouse.wheel(0,-300);
  await page.locator('#reset-view').click();
  await page.locator('[data-filter="usdt"]').click();
  await page.locator('#volume-input').fill('8');
  await page.waitForFunction(()=>document.querySelector('#scale-low').textContent==='8.00M');
  assert.match(await page.locator('#scale-low').innerText(),/8/);
  await page.locator('[data-period="1d"]').click();
  await page.waitForFunction(()=>document.querySelector('#price-range').textContent==='±5%');
  assert.equal(await page.locator('#volume-input').inputValue(),'5');
  await page.locator('[data-filter="percentile"]').click();
  await page.locator('#percentile-low').fill('70');await page.locator('#percentile-low').dispatchEvent('input');
  await page.locator('[data-period="1w"]').click();
  await page.waitForFunction(()=>document.querySelector('#price-range').textContent==='±10%');
  assert.equal(await page.locator('#volume-input').inputValue(),'8');
  assert.equal(await page.locator('[data-filter="usdt"]').getAttribute('aria-pressed'),'true');
  await page.locator('[data-filter="percentile"]').click();
  assert.equal(await page.locator('#percentile-low').inputValue(),'85');
  await page.locator('[data-filter="usdt"]').click();
  await page.locator('#volume-input').fill('5');
  await page.locator('[data-period="1d"]').click();
  await page.waitForFunction(()=>document.querySelector('#price-range').textContent==='±5%');
  assert.equal(await page.locator('[data-filter="percentile"]').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('#percentile-low').inputValue(),'70');
  await page.locator('[data-filter="usdt"]').click();
  await page.locator('[data-cvd="absolute"]').click();
  assert.equal(await page.locator('[data-cvd="absolute"]').getAttribute('aria-pressed'),'true');
  await page.locator('#zoom-in').click();await page.locator('#zoom-out').click();await page.locator('#reset-view').click();
  await page.locator('#controls-help summary').click();
  assert.match(await page.locator('#controls-help').innerText(),/С ПК/);
  assert.match(await page.locator('#controls-help').innerText(),/С телефона/);
  assert.match(await page.locator('#controls-help').innerText(),/Shift/);
  await page.locator('#controls-help summary').click();
  await page.locator('#price-step').click();
  assert.equal(await page.locator('#price-step').inputValue(),'');
  assert.equal(await page.locator('#price-step').getAttribute('placeholder'),'25–2000');
  await page.locator('.settings-heading h2').click();
  assert.equal(await page.locator('#price-step').inputValue(),'200','Empty edit must restore the previous value');
  await page.locator('#price-margin').click();
  assert.equal(await page.locator('#price-margin').inputValue(),'');
  assert.equal(await page.locator('#price-margin').getAttribute('placeholder'),'0.5–20');
  await page.locator('.settings-heading h2').click();
  assert.equal(await page.locator('#price-margin').inputValue(),'5');
  await page.locator('#price-step').fill('100');
  await page.locator('#price-margin').fill('3');
  await page.locator('#apply-price').click();
  await page.waitForFunction(()=>document.querySelector('#price-range').textContent==='±3%');
  assert.equal(await page.locator('[data-period="1d"] span').innerText(),'±3%');
  const custom=await (await page.request.get(fixture.base+'/api/chart?mode=1d&step=100&range=3')).json();
  assert.equal(custom.price_step,100);assert.equal(custom.price_margin_pct,3);
  await page.locator('#price-step').fill('33');await page.locator('#apply-price').click();
  await page.locator('#price-settings-error').waitFor({state:'visible'});
  await page.locator('#price-step').fill('200');await page.locator('#price-margin').fill('5');
  await page.locator('#apply-price').click();
  await page.waitForFunction(()=>document.querySelector('#price-range').textContent==='±5%');
  assert.equal((await context.cookies()).length,process.env.MTANALOG_BROWSER_LINK_FILE?1:0);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'output/web_mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile horizontal overflow');
  // Chromium delivers actual touch events, exercising pointer capture and pinch.
  await page.locator('#heatmap').scrollIntoViewIfNeeded();
  const mobileHeat=await page.locator('#heatmap').boundingBox();
  const session=await context.newCDPSession(page);
  const x=mobileHeat.x+mobileHeat.width*.5,y=mobileHeat.y+mobileHeat.height*.45;
  const before=await page.locator('#heatmap').screenshot();
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-25,y,id:1},{x:x+25,y,id:2}]});
  await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-65,y,id:1},{x:x+65,y,id:2}]});
  await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  const after=await page.locator('#heatmap').screenshot();
  assert.ok(!before.equals(after),'Pinch must change the drawn chart');
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:3}]});
  await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+35,y,id:3}]});
  await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  const panned=await page.locator('#heatmap').screenshot();assert.ok(!after.equals(panned),'Swipe must move time');
  const right=mobileHeat.x+mobileHeat.width-25;
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:right,y,id:4}]});
  await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:right,y:y-50,id:4}]});
  await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  const scaled=await page.locator('#heatmap').screenshot();assert.ok(!panned.equals(scaled),'Right edge swipe must change price scale');
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:5}]});
  await page.locator('#heatmap-tooltip').waitFor({state:'visible'});
  assert.match(await page.locator('#heatmap-tooltip').innerText(),/Объём/);
  const loupe=page.locator('.chart-loupe:visible');
  await loupe.waitFor({state:'visible'});
  const center=await loupe.evaluate(el=>({x:Number(el.dataset.centerX),y:Number(el.dataset.centerY)}));
  assert.ok(Math.hypot(center.x-(x-mobileHeat.x),center.y-(y-mobileHeat.y))>=80,'Crosshair must stay clear of the finger');
  assert.equal(await loupe.evaluate(el=>getComputedStyle(el).borderRadius),'50%');
  await page.screenshot({path:'output/web_inspection_mobile.png'});
  const inspection=await page.locator('#heatmap-tooltip small').innerText();
  await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+25,y,id:5}]});
  assert.notEqual(await page.locator('#heatmap-tooltip small').innerText(),inspection,'Hold drag must move the crosshair');
  await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await page.locator('#heatmap-tooltip').waitFor({state:'visible'});
  // A new quick swipe hides inspection and remains a time drag.
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:6}]});
  await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+30,y,id:6}]});
  await page.waitForTimeout(650);
  await page.locator('#heatmap-tooltip').waitFor({state:'hidden'});
  assert.equal(await page.locator('.chart-loupe:visible').count(),0);
  await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await page.locator('#cvd').scrollIntoViewIfNeeded();
  const cvdBox=await page.locator('#cvd').boundingBox(),cx=cvdBox.x+cvdBox.width*.45,cy=cvdBox.y+cvdBox.height*.45;
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx,y:cy,id:7}]});
  await page.locator('#cvd-tooltip').waitFor({state:'visible'});
  assert.match(await page.locator('#cvd-tooltip').innerText(),/Все исполнения/);
  assert.equal(await page.locator('.chart-loupe:visible').count(),1);
  await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await page.emulateMedia({reducedMotion:'reduce'});
  const phoneContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:3});
  const phone=await phoneContext.newPage();phone.on('pageerror',error=>errors.push(error.message));
  await phone.goto(fixture.base);await phone.locator('#loading').waitFor({state:'hidden'});
  assert.equal(await phone.locator('html').getAttribute('data-client'),'touch');
  await phone.locator('#connection').tap(); // Establish actual touch input without navigating.
  assert.equal(await phone.locator('html').getAttribute('data-input'),'touch');
  assert.match(await phone.locator('.chart-hint').innerText(),/Удержание/);
  assert.ok((await phone.locator('#refresh').boundingBox()).height>=43.5,'Phone controls need touch targets');
  await phone.screenshot({path:'output/web_phone.png'});
  assert.equal(await phone.locator('html').getAttribute('data-client'),'touch');
  await phone.locator('#price-step').scrollIntoViewIfNeeded();
  const editBox=await phone.locator('#price-step').boundingBox();
  await phone.touchscreen.tap(editBox.x+editBox.width/2,editBox.y+editBox.height/2);
  assert.equal(await phone.locator('#price-step').inputValue(),'');
  await phone.locator('#price-step').evaluate(el=>el.blur());
  assert.equal(await phone.locator('#price-step').inputValue(),'200');
  await phone.setViewportSize({width:844,height:390});
  const phoneSession=await phoneContext.newCDPSession(phone);
  await phoneSession.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});
  await phone.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  assert.equal(await phone.locator('html').getAttribute('data-client'),'touch');
  assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Phone landscape horizontal overflow');
  const phoneMain=await phone.locator('.main-column').boundingBox(),phoneSide=await phone.locator('.sidebar').boundingBox();
  assert.ok(phoneSide.y>phoneMain.y,'Touch landscape settings must sit below charts');
  await phoneContext.close();
  assert.deepEqual(errors,[]);
  console.log('Browser checks passed: public access, read-only API, periods, filters, CVD, tooltip, zoom, price settings, mobile pinch/swipe/price scale, offset crosshair and loupe, desktop sizes/keyboard, real phone detection and landscape, control help and clear-on-edit fields.');
}finally{await browser.close();}
