import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const source=await fs.readFile(new URL('../mtanalog/static/chart.js',import.meta.url),'utf8');
const {Charts,anchoredRange,inspectionPoint}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
const view=anchoredRange([.2,.8],.5,.25);
near(view[0]+(view[1]-view[0])*.25,.2+.6*.25);
assert.deepEqual(anchoredRange([0,1],.5,1),[.5,1]);
assert.deepEqual(anchoredRange([.2,.8],100,.5),[0,1]);
const canvas={getBoundingClientRect:()=>({left:0,top:0,width:1000,height:500}),setPointerCapture(){}};
const chart=Object.create(Charts.prototype);
Object.assign(chart,{data:{low:70000,high:90000},heat:canvas,view:[.2,.8],priceView:[.2,.8],touches:new Map(),left:16,right:68,hideTips(){},draw(){}});
const event=(id,x,y)=>({pointerId:id,clientX:x,clientY:y,button:0,preventDefault(){}});
chart.down(event(1,300,200),canvas);chart.down(event(2,600,200),canvas);
const initial=chart.drag,anchor=(450-16)/916,point=.2+.6*anchor;
chart.gesture(event(1,150,200),canvas);chart.gesture(event(2,750,200),canvas);
near(chart.view[1]-chart.view[0],.3);near(chart.view[0]+.3*anchor,point);
near(chart.priceView[1]-chart.priceView[0],.3);
chart.up(event(2,750,200),canvas);
const previous=[...chart.view];chart.gesture(event(1,200,200),canvas);
near(chart.view[0],previous[0]-50/916*.3);
chart.up(event(1,200,200),canvas);assert.equal(chart.drag,null);
chart.down(event(3,970,200),canvas);const time=[...chart.view],span=chart.priceView[1]-chart.priceView[0];
chart.gesture(event(3,970,150),canvas);assert.deepEqual(chart.view,time);assert.ok(chart.priceView[1]-chart.priceView[0]<span);
chart.up(event(3,970,150),canvas);chart.reset();assert.deepEqual(chart.priceView,[0,1]);
console.log('Chart gesture checks passed: anchored zoom, pinch, transition to pan, price scale, reset.');
const originalMove=chart.move;let inspected=false;
chart.move=()=>{inspected=true;};
const touch=(id,x,y)=>({...event(id,x,y),pointerType:'touch'});
chart.down(touch(4,300,200),canvas);
await new Promise(resolve=>setTimeout(resolve,600));
assert.ok(inspected);assert.equal(chart.drag.kind,'inspect');
const heldView=[...chart.view];assert.equal(chart.gesture(touch(4,350,200),canvas),false);assert.deepEqual(chart.view,heldView);
chart.up(touch(4,350,200),canvas);
inspected=false;chart.down(touch(5,300,200),canvas);chart.gesture(touch(5,330,200),canvas);
await new Promise(resolve=>setTimeout(resolve,600));assert.equal(inspected,false);chart.up(touch(5,330,200),canvas);
chart.down(touch(6,300,200),canvas);chart.down(touch(7,500,200),canvas);
await new Promise(resolve=>setTimeout(resolve,600));assert.equal(inspected,false);assert.equal(chart.drag.kind,'pinch');
chart.up(touch(6,300,200),canvas);chart.up(touch(7,500,200),canvas);chart.move=originalMove;
console.log('Long-press checks passed: inspection keeps time fixed; swipe and second finger cancel hold.');

const plot={x:16,y:8,w:300,h:300};
assert.deepEqual(inspectionPoint(160,180,plot,{x:48,y:-90}),{x:208,y:90});
assert.deepEqual(inspectionPoint(20,20,plot,{x:-48,y:-90}),{x:16,y:8});
const lines=[],context={setLineDash(){},beginPath(){},moveTo(x,y){lines.push(['move',x,y]);},lineTo(x,y){lines.push(['line',x,y]);},stroke(){}};
chart.pointer={x:140,y:90,canvas};chart.drawCrosshair(context,plot,canvas);
assert.deepEqual(lines,[['move',140,8],['line',140,308],['move',16,90],['line',316,90]]);
console.log('Inspection checks passed: offset bounds and both crosshair axes.');

chart.pointer=null;chart.view=[.25,.75];chart.pan(.2);near(chart.view[0],.35);near(chart.view[1],.85);chart.pan(5);assert.deepEqual(chart.view,[.5,1]);chart.pan(-5);assert.deepEqual(chart.view,[0,.5]);
console.log('Desktop pan checks passed: time moves and remains inside the archive.');

const {aggregateCandles}=await import('../mtanalog/static/chart.js');
const combined=aggregateCandles([{time:0,open:100,high:110,low:80,close:105},{time:60,open:105,high:120,low:100,close:115}],5);
assert.equal(combined.length,1);assert.equal(combined[0].low,80);assert.equal(combined[0].high,120);assert.equal(combined[0].close,115);
console.log('Candle aggregation preserves intraminute extremes.');
